### PR TITLE
Support shards package manager

### PR DESCRIPTION
**Pull request by pine**
Hi.

Crystal `>= v0.8.0` has new package manager named [shards](https://github.com/ysbaddaden/shards).
`crystal deps` sub command is redirecting to shards now.

I want to use `crystal-mysql` in Crystal v0.8.0...

### CODE REVIEW

**Comment by alex-fedorov** [comment]
I have pushed update to the master that fixes code to work with Crystal 0.8.0. You may want to rebase your branch and re-push it. Should be green on CI after that.

**Comment by pine** [comment]
Thank you!! I've re-pushed.

**Comment by waterlink** [comment]
:+1: Thank you!

**Comment by pine** [comment]
:+1:

**Pull request merged**
